// <auto-generated />
using System;
using IOM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOM.Data.Migrations
{
    [DbContext(typeof(IOMContext))]
    [Migration("20210320050738_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ade0ece-b49d-4951-bda7-0a50cc4fc498"),
                            CreatedDate = new DateTime(2021, 3, 18, 23, 2, 25, 227, DateTimeKind.Local).AddTicks(3710),
                            Number = "8608",
                            Total = "5778",
                            UserId = new Guid("b40b24f4-0e64-4d8f-9709-c84160776bd8")
                        },
                        new
                        {
                            Id = new Guid("d4eaa2f8-0d13-445f-8014-e615ee0de36d"),
                            CreatedDate = new DateTime(2021, 3, 19, 7, 51, 44, 433, DateTimeKind.Local).AddTicks(1161),
                            Number = "9150",
                            Total = "8023",
                            UserId = new Guid("3f65a7e4-3ce0-4dea-b2a9-bb8bb12cee2a")
                        },
                        new
                        {
                            Id = new Guid("a417cd12-32b1-4f35-b2c8-9947fa1fe38a"),
                            CreatedDate = new DateTime(2021, 3, 19, 5, 1, 55, 954, DateTimeKind.Local).AddTicks(9698),
                            Number = "7199",
                            Total = "4862",
                            UserId = new Guid("e7da8ccf-9616-49a1-9910-18e0935ba85b")
                        },
                        new
                        {
                            Id = new Guid("9e7c0998-65f9-4885-bf11-59120b732d69"),
                            CreatedDate = new DateTime(2021, 3, 19, 17, 45, 34, 480, DateTimeKind.Local).AddTicks(1988),
                            Number = "7574",
                            Total = "5911",
                            UserId = new Guid("da953856-f9fa-4247-aa82-4fdc34c9c16f")
                        },
                        new
                        {
                            Id = new Guid("d88460ae-8c14-4fa5-99fa-27e6996ff589"),
                            CreatedDate = new DateTime(2021, 3, 19, 1, 58, 36, 24, DateTimeKind.Local).AddTicks(874),
                            Number = "3845",
                            Total = "7154",
                            UserId = new Guid("59b78cc3-f5c3-47df-ace0-7a48ed183929")
                        },
                        new
                        {
                            Id = new Guid("af175a51-ad02-4027-9120-c5d30af913f0"),
                            CreatedDate = new DateTime(2021, 3, 19, 21, 59, 5, 218, DateTimeKind.Local).AddTicks(3449),
                            Number = "6141",
                            Total = "3201",
                            UserId = new Guid("e7da8ccf-9616-49a1-9910-18e0935ba85b")
                        },
                        new
                        {
                            Id = new Guid("6ce4fe84-4ae0-4a79-be9b-4492fd0e250c"),
                            CreatedDate = new DateTime(2021, 3, 19, 19, 54, 16, 394, DateTimeKind.Local).AddTicks(3077),
                            Number = "2880",
                            Total = "3854",
                            UserId = new Guid("3f65a7e4-3ce0-4dea-b2a9-bb8bb12cee2a")
                        },
                        new
                        {
                            Id = new Guid("5f471f2e-fd20-483b-8ac7-7dc95106249b"),
                            CreatedDate = new DateTime(2021, 3, 19, 12, 28, 28, 459, DateTimeKind.Local).AddTicks(1939),
                            Number = "2041",
                            Total = "9133",
                            UserId = new Guid("5f45814a-1396-46a6-a597-519cc933db09")
                        },
                        new
                        {
                            Id = new Guid("60c64789-c77a-4b37-9663-07f4f6f8ad40"),
                            CreatedDate = new DateTime(2021, 3, 19, 4, 25, 14, 503, DateTimeKind.Local).AddTicks(5528),
                            Number = "7099",
                            Total = "1389",
                            UserId = new Guid("5f45814a-1396-46a6-a597-519cc933db09")
                        },
                        new
                        {
                            Id = new Guid("75c6c68e-1e1c-4419-8e6a-9c94f54a869a"),
                            CreatedDate = new DateTime(2021, 3, 19, 13, 13, 53, 318, DateTimeKind.Local).AddTicks(6906),
                            Number = "4",
                            Total = "4700",
                            UserId = new Guid("09154fe6-7192-4c07-81ec-2f062221dca8")
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoiceId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceSupplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId", "InvoiceId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceSuppliers");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("740ab68b-419c-451b-895e-9800dab41860"),
                            ProductId = new Guid("49b5185b-0213-4175-a638-bf4978956c82")
                        },
                        new
                        {
                            Id = new Guid("f821b235-0335-489d-a0ec-5c8546eb006b"),
                            ProductId = new Guid("ccc92b47-718b-4b23-a0e0-4d3f456a4e64")
                        },
                        new
                        {
                            Id = new Guid("480fdbeb-4408-4938-9b73-11e8feb2659c"),
                            ProductId = new Guid("ccc92b47-718b-4b23-a0e0-4d3f456a4e64")
                        },
                        new
                        {
                            Id = new Guid("9f0e6215-3808-4095-a381-eda6a7284b21"),
                            ProductId = new Guid("cbb92643-3463-4517-9cd7-e8cdc3191a07")
                        },
                        new
                        {
                            Id = new Guid("f524fdb6-6a04-4aae-8d5c-71624543958c"),
                            ProductId = new Guid("4e71823f-fe44-4308-9e2a-8a1dd426b3d0")
                        },
                        new
                        {
                            Id = new Guid("90639fcd-1991-4906-9544-8e1944b782bf"),
                            ProductId = new Guid("7c945bf4-584e-4a53-8572-6890432251f1")
                        },
                        new
                        {
                            Id = new Guid("195f6b61-8a14-459a-9b24-081d5cb03f12"),
                            ProductId = new Guid("2e4561e8-428c-406d-b347-afe7edaf1c43")
                        },
                        new
                        {
                            Id = new Guid("ffca3879-39c3-40fa-bf48-7d2e364a3712"),
                            ProductId = new Guid("7c945bf4-584e-4a53-8572-6890432251f1")
                        },
                        new
                        {
                            Id = new Guid("f401c5a9-6ea3-4daf-9df4-4564125dd2cd"),
                            ProductId = new Guid("1895644f-7117-4fe0-801f-4e9c5682f5a9")
                        },
                        new
                        {
                            Id = new Guid("c813ab6e-9ad8-442a-a03c-510bdc2eda2f"),
                            ProductId = new Guid("2e4561e8-428c-406d-b347-afe7edaf1c43")
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaa8df7f-83c3-4917-937b-efe170f3e9a3"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Cotton Keyboard",
                            Price = 109.90m
                        },
                        new
                        {
                            Id = new Guid("2e4561e8-428c-406d-b347-afe7edaf1c43"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Soft Table",
                            Price = 12.20m
                        },
                        new
                        {
                            Id = new Guid("ccc92b47-718b-4b23-a0e0-4d3f456a4e64"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Licensed Steel Chair",
                            Price = 382.71m
                        },
                        new
                        {
                            Id = new Guid("49b5185b-0213-4175-a638-bf4978956c82"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Gorgeous Metal Bike",
                            Price = 89.91m
                        },
                        new
                        {
                            Id = new Guid("4e71823f-fe44-4308-9e2a-8a1dd426b3d0"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Plastic Gloves",
                            Price = 896.06m
                        },
                        new
                        {
                            Id = new Guid("1895644f-7117-4fe0-801f-4e9c5682f5a9"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Licensed Metal Sausages",
                            Price = 692.14m
                        },
                        new
                        {
                            Id = new Guid("cbb92643-3463-4517-9cd7-e8cdc3191a07"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Frozen Computer",
                            Price = 341.71m
                        },
                        new
                        {
                            Id = new Guid("ad4b37a3-6068-4752-b0d3-facce5f34e59"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Metal Fish",
                            Price = 93.97m
                        },
                        new
                        {
                            Id = new Guid("afb40ba1-8194-45a0-b9e9-c96df0cf021a"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Concrete Ball",
                            Price = 961.61m
                        },
                        new
                        {
                            Id = new Guid("7c945bf4-584e-4a53-8572-6890432251f1"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Steel Shoes",
                            Price = 486.17m
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("765eec08-18e9-4d3c-9f47-4c6ea70bdf77"),
                            Name = "Predovic Group"
                        },
                        new
                        {
                            Id = new Guid("10224046-fef3-44e0-85f1-90108ae50612"),
                            Name = "MacGyver Inc"
                        },
                        new
                        {
                            Id = new Guid("3e5d8e8a-7e48-4639-b6ef-5ea3cdd21bef"),
                            Name = "White and Sons"
                        },
                        new
                        {
                            Id = new Guid("85f0b92f-fffa-4998-a44b-952e18c3463d"),
                            Name = "Kuvalis - Schowalter"
                        },
                        new
                        {
                            Id = new Guid("7fdbcc31-1f43-4a72-a36a-ce07811b36ed"),
                            Name = "Bartell, Bode and Turner"
                        },
                        new
                        {
                            Id = new Guid("832eb7b4-5471-489e-bd0c-e6812777bdf6"),
                            Name = "Steuber Group"
                        },
                        new
                        {
                            Id = new Guid("85b45c2a-3e34-43a3-b633-d2dd0a8bad8d"),
                            Name = "Emard - McDermott"
                        },
                        new
                        {
                            Id = new Guid("360c8591-a98c-4483-8385-935eefca7bc7"),
                            Name = "Bode - Ziemann"
                        },
                        new
                        {
                            Id = new Guid("3bb7e13c-4e9f-4bb8-955b-cacf14f00a96"),
                            Name = "Langworth - Lockman"
                        },
                        new
                        {
                            Id = new Guid("61d97d8e-7893-41a1-9339-90362b64cf1b"),
                            Name = "Kuphal - Grimes"
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.SupplierProduct", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupplierProducts");
                });

            modelBuilder.Entity("IOM.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f45814a-1396-46a6-a597-519cc933db09"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Delores",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("e7da8ccf-9616-49a1-9910-18e0935ba85b"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Bernita",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("3d9ed7e0-14dc-4359-bae0-6f74dfe7c4c4"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Jamir",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("09154fe6-7192-4c07-81ec-2f062221dca8"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Oleta",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("3f65a7e4-3ce0-4dea-b2a9-bb8bb12cee2a"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Madyson",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("7cb7d9ba-9429-408d-a2cc-b50e00acf1bd"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Holly",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("59b78cc3-f5c3-47df-ace0-7a48ed183929"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Fidel",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("da953856-f9fa-4247-aa82-4fdc34c9c16f"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Tyree",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("b40b24f4-0e64-4d8f-9709-c84160776bd8"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Barrett",
                            Password = "password123"
                        },
                        new
                        {
                            Id = new Guid("6141e820-569b-4124-b3ac-5aad62de303c"),
                            Email = "aajmeri7@gmail.com",
                            Name = "Lucy",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.HasOne("IOM.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceItem", b =>
                {
                    b.HasOne("IOM.Core.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Item", "Item")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceSupplier", b =>
                {
                    b.HasOne("IOM.Core.Models.Invoice", "Invoice")
                        .WithMany("InvoiceSupplier")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Supplier", "Supplier")
                        .WithMany("InvoiceSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.HasOne("IOM.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOM.Core.Models.SupplierProduct", b =>
                {
                    b.HasOne("IOM.Core.Models.Product", "Product")
                        .WithMany("SupplierProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Supplier", "Supplier")
                        .WithMany("SupplierProduct")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItem");

                    b.Navigation("InvoiceSupplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("IOM.Core.Models.Product", b =>
                {
                    b.Navigation("SupplierProduct");
                });

            modelBuilder.Entity("IOM.Core.Models.Supplier", b =>
                {
                    b.Navigation("InvoiceSuppliers");

                    b.Navigation("SupplierProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
