// <auto-generated />
using System;
using IOM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOM.Data.Migrations
{
    [DbContext(typeof(IOMContext))]
    [Migration("20210320052021_AddMoreProductsAndItems")]
    partial class AddMoreProductsAndItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoiceId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceSupplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId", "InvoiceId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceSuppliers");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("825f0043-6934-48f4-93e8-e0ab1c68ba47"),
                            ProductId = new Guid("8615a7a3-078b-45c8-9d6a-831e125e4916")
                        },
                        new
                        {
                            Id = new Guid("f83a144e-fd4c-4ae0-bc67-227007caef34"),
                            ProductId = new Guid("d8bdd3f3-0b97-4110-8233-b06bc1abf3d7")
                        },
                        new
                        {
                            Id = new Guid("38ae1e84-f445-4a14-adf9-f7b9a59be993"),
                            ProductId = new Guid("fae36503-1517-41b1-91b0-173e7cea66cc")
                        },
                        new
                        {
                            Id = new Guid("a67ebf76-0e51-4aae-9316-6d59eceab693"),
                            ProductId = new Guid("84fd00e6-586b-4333-a806-a0b524a3b232")
                        },
                        new
                        {
                            Id = new Guid("9c014e4f-2d5c-484b-8d31-2f64fb7b736f"),
                            ProductId = new Guid("75c94cdd-c710-4917-b3fc-6ed5d9dfc76c")
                        },
                        new
                        {
                            Id = new Guid("9fcd2510-2aec-4375-9881-1904c47ef34c"),
                            ProductId = new Guid("29e392c9-3375-4a60-9322-a72154b4b83f")
                        },
                        new
                        {
                            Id = new Guid("5fd3d053-15e7-4830-8a9e-0692f89940a3"),
                            ProductId = new Guid("d6eeacf3-abad-4c53-ab41-59a43801857b")
                        },
                        new
                        {
                            Id = new Guid("034d233b-53d4-4260-92f4-bb773a1e473a"),
                            ProductId = new Guid("2ce63658-f846-48fb-8021-2cdbdf658bdc")
                        },
                        new
                        {
                            Id = new Guid("3199bd5c-fa7e-4a7d-9676-c33523357c07"),
                            ProductId = new Guid("e7f2b5e3-db46-4d84-af30-9b1ced62a9d8")
                        },
                        new
                        {
                            Id = new Guid("da628acd-66f2-425b-806b-ab718e393374"),
                            ProductId = new Guid("3f455689-154a-4461-9241-1bab66de5495")
                        },
                        new
                        {
                            Id = new Guid("7c5af048-e8fd-4fc0-bf0e-52a3d3f8c170"),
                            ProductId = new Guid("b5a53c24-820b-4499-a14a-11da946a04fb")
                        },
                        new
                        {
                            Id = new Guid("17778bba-7fd3-4bdc-abf5-d6937d72eb0c"),
                            ProductId = new Guid("2e56538b-5589-401c-8d1a-c034fef15d3c")
                        },
                        new
                        {
                            Id = new Guid("244bcacf-bd10-4bed-a80c-6aa9e426ed4e"),
                            ProductId = new Guid("a44ac53f-8536-40a6-85b2-b70db3c64c1a")
                        },
                        new
                        {
                            Id = new Guid("4dcb0baf-a626-4360-bcd1-9a28d61c916e"),
                            ProductId = new Guid("ff2ebfd5-49eb-40f3-9ab4-216ce34ab7ef")
                        },
                        new
                        {
                            Id = new Guid("c4290f57-0bf5-4b21-8c5b-88e26355c960"),
                            ProductId = new Guid("9f888ca1-56e5-4b88-b658-7654250009cf")
                        },
                        new
                        {
                            Id = new Guid("3a240826-bca1-4104-b823-765ed61470db"),
                            ProductId = new Guid("72305cfe-bcbf-49bc-b9a2-40b22195f349")
                        },
                        new
                        {
                            Id = new Guid("51899001-462a-4468-82ad-13e23e0219f9"),
                            ProductId = new Guid("1c681462-8681-4690-a689-5ac18ec656ae")
                        },
                        new
                        {
                            Id = new Guid("bda7a401-d232-4081-ad6d-593b09d98356"),
                            ProductId = new Guid("751c2f3e-8df1-4a82-b7f1-7f5375d3e9c2")
                        },
                        new
                        {
                            Id = new Guid("10412d1a-0ced-400d-9b30-c41bdcdbc543"),
                            ProductId = new Guid("118afaa1-71b1-457c-9b6f-20fb21167b4d")
                        },
                        new
                        {
                            Id = new Guid("4ba3a023-6710-4235-b32b-4d9037003985"),
                            ProductId = new Guid("4396694e-958c-4bbe-a4e2-c8d7ff8e8ce9")
                        },
                        new
                        {
                            Id = new Guid("d65e7908-3dc7-4120-b2b3-ca41faedfc0e"),
                            ProductId = new Guid("9f888ca1-56e5-4b88-b658-7654250009cf")
                        },
                        new
                        {
                            Id = new Guid("50a8fb40-0bed-4434-9275-5f5f8f74b280"),
                            ProductId = new Guid("ff2ebfd5-49eb-40f3-9ab4-216ce34ab7ef")
                        },
                        new
                        {
                            Id = new Guid("484a2ed8-ab8f-4def-8acc-c0cff8149bac"),
                            ProductId = new Guid("bfe642ae-b013-4b57-9afd-4e156fb30af5")
                        },
                        new
                        {
                            Id = new Guid("3eebae61-ca1c-456e-9016-18f043100269"),
                            ProductId = new Guid("26d5b702-214c-4e07-88e4-4f647d77e4bc")
                        },
                        new
                        {
                            Id = new Guid("c3ac26fb-0400-4342-bb47-3ed130d7a1ae"),
                            ProductId = new Guid("aa5eb30d-dfff-468f-9e75-7dd99135785d")
                        },
                        new
                        {
                            Id = new Guid("5de935c5-1d20-4a44-aef7-0a0c70542703"),
                            ProductId = new Guid("f6503aa7-5815-4445-baf5-9b57be57d5b1")
                        },
                        new
                        {
                            Id = new Guid("617c22a5-b50f-4c78-a5fa-4779fbcb1d17"),
                            ProductId = new Guid("c6ee0204-703d-424e-b012-eed78b6885b5")
                        },
                        new
                        {
                            Id = new Guid("a7df641b-2ffc-4493-89dd-ebbd81626d85"),
                            ProductId = new Guid("5b6fc1c4-88b3-40da-8c9e-5dc0d8d5b5cd")
                        },
                        new
                        {
                            Id = new Guid("ffbbdd2a-31a9-46e7-8e51-bd24f34f059d"),
                            ProductId = new Guid("29e392c9-3375-4a60-9322-a72154b4b83f")
                        },
                        new
                        {
                            Id = new Guid("d743c207-a32d-4241-9bf5-fc7e6a5560b0"),
                            ProductId = new Guid("170d6671-45e0-4e64-90ad-aad7fe9ebf1d")
                        },
                        new
                        {
                            Id = new Guid("c708ec26-d9a1-4ee2-af18-392565a635f9"),
                            ProductId = new Guid("21dd46a4-ad83-4c36-867a-aa01620ef9ee")
                        },
                        new
                        {
                            Id = new Guid("b4078c6a-3a53-4805-bb90-c1e8b6a699bf"),
                            ProductId = new Guid("26d5b702-214c-4e07-88e4-4f647d77e4bc")
                        },
                        new
                        {
                            Id = new Guid("7acaa69a-35ad-40c8-a730-a2d22eed554b"),
                            ProductId = new Guid("5a2bb5a9-3f55-411f-af4f-9cd45bbf1e4f")
                        },
                        new
                        {
                            Id = new Guid("7de9f1d1-5c9d-48fe-9c42-20fde891b965"),
                            ProductId = new Guid("3f455689-154a-4461-9241-1bab66de5495")
                        },
                        new
                        {
                            Id = new Guid("69bccdc0-3196-424f-bb9f-75f465429513"),
                            ProductId = new Guid("55d8bbdb-f798-439a-8cc3-58b9716f72e6")
                        },
                        new
                        {
                            Id = new Guid("38992019-a877-4cde-bf10-eb42ddeff355"),
                            ProductId = new Guid("b5a53c24-820b-4499-a14a-11da946a04fb")
                        },
                        new
                        {
                            Id = new Guid("c5e90c4c-3224-42ec-833f-ff0934cb9799"),
                            ProductId = new Guid("757a63d5-4367-4c5c-98a1-bffb60172f15")
                        },
                        new
                        {
                            Id = new Guid("7016ad12-312e-4507-afa7-9bdc58a682ec"),
                            ProductId = new Guid("5b6fc1c4-88b3-40da-8c9e-5dc0d8d5b5cd")
                        },
                        new
                        {
                            Id = new Guid("4accf78a-57e3-40fa-8934-ab5f52b08fe0"),
                            ProductId = new Guid("3956c3d8-aa5f-48d4-8428-65fe82e40c25")
                        },
                        new
                        {
                            Id = new Guid("5c1a3d35-f8fd-4fe6-b330-c54188279280"),
                            ProductId = new Guid("db25efaf-4958-4671-8f8e-5fa97464a243")
                        },
                        new
                        {
                            Id = new Guid("e3074660-2ea1-4ff4-bc79-ee39e1840c28"),
                            ProductId = new Guid("2734d4ec-6ddc-4d6b-aba2-80b0b0ce7142")
                        },
                        new
                        {
                            Id = new Guid("173e9db4-a9e0-48d1-8d17-7ae027a4093a"),
                            ProductId = new Guid("170d6671-45e0-4e64-90ad-aad7fe9ebf1d")
                        },
                        new
                        {
                            Id = new Guid("c056e375-7799-4dbb-b43f-6119507a8adc"),
                            ProductId = new Guid("b5a53c24-820b-4499-a14a-11da946a04fb")
                        },
                        new
                        {
                            Id = new Guid("886db569-4293-4f0d-82be-80c94f7bd705"),
                            ProductId = new Guid("bfe642ae-b013-4b57-9afd-4e156fb30af5")
                        },
                        new
                        {
                            Id = new Guid("761bb9b5-eea0-489b-b915-3e7fa66b2e7c"),
                            ProductId = new Guid("a00a44fc-59c8-4457-b490-ce736284b9b3")
                        },
                        new
                        {
                            Id = new Guid("1b5963a9-7fd5-4491-9325-9df69eb6f90b"),
                            ProductId = new Guid("3956c3d8-aa5f-48d4-8428-65fe82e40c25")
                        },
                        new
                        {
                            Id = new Guid("20e83bc9-1bb6-4ee0-83aa-409ce2798ad1"),
                            ProductId = new Guid("21dd46a4-ad83-4c36-867a-aa01620ef9ee")
                        },
                        new
                        {
                            Id = new Guid("8c60acd0-29d0-4e5d-adab-ca2b08ecb189"),
                            ProductId = new Guid("62f2448a-c310-452d-afc0-f3a95e9e872a")
                        },
                        new
                        {
                            Id = new Guid("51afa89b-e5f4-48bc-9305-99c207265c88"),
                            ProductId = new Guid("966c6717-c62b-4f4a-8780-a899e60cf011")
                        },
                        new
                        {
                            Id = new Guid("da2ddefc-8c73-4ae3-90e0-95ca5c6ccfa7"),
                            ProductId = new Guid("b17e13ee-e85f-4e0d-8865-6ca1abb9c599")
                        },
                        new
                        {
                            Id = new Guid("70d44373-36ba-42b9-be3a-828d63cf13db"),
                            ProductId = new Guid("80e192c5-5c04-4cca-8f21-caaf0cafcdef")
                        },
                        new
                        {
                            Id = new Guid("7dbb41cc-6d7c-42ee-b931-96ea13f9e557"),
                            ProductId = new Guid("b5a53c24-820b-4499-a14a-11da946a04fb")
                        },
                        new
                        {
                            Id = new Guid("c4846de3-0a6c-4e79-b5f6-148916b748c9"),
                            ProductId = new Guid("4396694e-958c-4bbe-a4e2-c8d7ff8e8ce9")
                        },
                        new
                        {
                            Id = new Guid("6cf6c19d-e9b8-4b8b-8fba-940bd70aa2a3"),
                            ProductId = new Guid("c935f927-dbff-4a15-998f-c43fae82686f")
                        },
                        new
                        {
                            Id = new Guid("97ba90d6-f2ad-474d-9fc9-8941c6901699"),
                            ProductId = new Guid("3956c3d8-aa5f-48d4-8428-65fe82e40c25")
                        },
                        new
                        {
                            Id = new Guid("af81854a-372e-4b4e-8aee-81bf1bf2ca45"),
                            ProductId = new Guid("fae36503-1517-41b1-91b0-173e7cea66cc")
                        },
                        new
                        {
                            Id = new Guid("39a755e9-f10f-49b1-a781-dfd9451e661c"),
                            ProductId = new Guid("70559fd9-637a-4b7a-9e66-9d15c1a7707a")
                        },
                        new
                        {
                            Id = new Guid("d35c8ca4-454b-4473-98ae-b5f2aa7d0434"),
                            ProductId = new Guid("9f888ca1-56e5-4b88-b658-7654250009cf")
                        },
                        new
                        {
                            Id = new Guid("ec50e6ec-22dc-43d9-aa92-099d1f01c00c"),
                            ProductId = new Guid("af08bec1-b8d7-4718-bfb7-6eade8c3f6dc")
                        },
                        new
                        {
                            Id = new Guid("d1553be8-83eb-40f0-a5ed-08277501ddeb"),
                            ProductId = new Guid("f13c577e-1f72-45a3-aff0-30b929242b76")
                        },
                        new
                        {
                            Id = new Guid("ff51fae4-854a-4428-bb5a-01527a7175eb"),
                            ProductId = new Guid("65a286a8-ccb1-4b8d-a36f-990fc4511ebf")
                        },
                        new
                        {
                            Id = new Guid("60f3c381-2b6c-465b-89cd-59b127d6c3cb"),
                            ProductId = new Guid("f2d23011-a3ab-4564-ab05-cd69fdb1a87b")
                        },
                        new
                        {
                            Id = new Guid("49f07a97-f0e5-4d9d-9260-7a87ecb74379"),
                            ProductId = new Guid("5db2271e-a20d-4a4e-90d4-dbf4a08a2c0f")
                        },
                        new
                        {
                            Id = new Guid("5989fd08-1c5c-43ef-83b3-cd5f269004c7"),
                            ProductId = new Guid("9f888ca1-56e5-4b88-b658-7654250009cf")
                        },
                        new
                        {
                            Id = new Guid("e575c3ab-898d-416d-a2e5-a7555c0f231e"),
                            ProductId = new Guid("fcbf01ea-4fa2-4ad0-8cc0-1787178a4b8c")
                        },
                        new
                        {
                            Id = new Guid("a8b665ae-9a8a-4f78-b1cf-4334586f61cf"),
                            ProductId = new Guid("95ccc587-3451-4816-b118-440c82846109")
                        },
                        new
                        {
                            Id = new Guid("2acfeccd-1054-4216-9b01-ad39d955d04c"),
                            ProductId = new Guid("a44ac53f-8536-40a6-85b2-b70db3c64c1a")
                        },
                        new
                        {
                            Id = new Guid("2b057359-7324-4244-a8df-3b5603fb146b"),
                            ProductId = new Guid("2ce63658-f846-48fb-8021-2cdbdf658bdc")
                        },
                        new
                        {
                            Id = new Guid("516295d3-7c91-4069-b1a7-b101f20aac6a"),
                            ProductId = new Guid("36883096-52c7-488a-94f1-0539a489f70d")
                        },
                        new
                        {
                            Id = new Guid("6a328fd5-fb77-412f-8107-0832a131bdde"),
                            ProductId = new Guid("c935f927-dbff-4a15-998f-c43fae82686f")
                        },
                        new
                        {
                            Id = new Guid("38efac0d-7baa-4a15-b8bf-4b0fc3d69bfa"),
                            ProductId = new Guid("04b4acc0-e4f3-4d16-9807-cd6a91f9445c")
                        },
                        new
                        {
                            Id = new Guid("a8ec5835-53cc-4e16-9dfe-e832c3feb96e"),
                            ProductId = new Guid("757a63d5-4367-4c5c-98a1-bffb60172f15")
                        },
                        new
                        {
                            Id = new Guid("7809304c-4e1e-485a-89e2-c2785ad09498"),
                            ProductId = new Guid("e1e42e20-a837-4c91-9bb2-b5ff0702f085")
                        },
                        new
                        {
                            Id = new Guid("bf948d5b-6a47-4cc5-834c-4dc0d9a64c22"),
                            ProductId = new Guid("2e4bf7a5-c43c-4280-8ed8-5dcddfb9bfab")
                        },
                        new
                        {
                            Id = new Guid("d320094b-cdb2-4c0e-ab79-f295aaa59d7b"),
                            ProductId = new Guid("77056e1d-bc25-4983-9738-09127b567cbb")
                        },
                        new
                        {
                            Id = new Guid("b14c119d-b7fb-4e85-b08b-e69910604a82"),
                            ProductId = new Guid("2e56538b-5589-401c-8d1a-c034fef15d3c")
                        },
                        new
                        {
                            Id = new Guid("e38683d9-dbfa-406e-be00-4028d606ab75"),
                            ProductId = new Guid("751c2f3e-8df1-4a82-b7f1-7f5375d3e9c2")
                        },
                        new
                        {
                            Id = new Guid("618d6577-bd25-4894-b9c9-a3bb765f482e"),
                            ProductId = new Guid("80e192c5-5c04-4cca-8f21-caaf0cafcdef")
                        },
                        new
                        {
                            Id = new Guid("a688714b-5f89-49e5-8175-ec6fec3a5fc8"),
                            ProductId = new Guid("c6ee0204-703d-424e-b012-eed78b6885b5")
                        },
                        new
                        {
                            Id = new Guid("f1a17dec-aeff-49c5-a119-456960ad13bb"),
                            ProductId = new Guid("80e192c5-5c04-4cca-8f21-caaf0cafcdef")
                        },
                        new
                        {
                            Id = new Guid("6219a60d-0155-457b-8ac5-eb3dd938141e"),
                            ProductId = new Guid("8fb764c3-63d9-4456-8e90-a5d8db79ab8d")
                        },
                        new
                        {
                            Id = new Guid("2de4ba6d-edb3-4af9-a2d0-ff7dd068665f"),
                            ProductId = new Guid("65a286a8-ccb1-4b8d-a36f-990fc4511ebf")
                        },
                        new
                        {
                            Id = new Guid("11cb025f-cc0b-4034-aa6d-2554324f9060"),
                            ProductId = new Guid("72305cfe-bcbf-49bc-b9a2-40b22195f349")
                        },
                        new
                        {
                            Id = new Guid("4928fd9a-7982-4815-8d51-ec6ab6e1c953"),
                            ProductId = new Guid("3df20c2a-6bab-472a-b469-fb797fd5c8c2")
                        },
                        new
                        {
                            Id = new Guid("e86925e0-b032-478f-bf1a-dffbdcb696db"),
                            ProductId = new Guid("3f455689-154a-4461-9241-1bab66de5495")
                        },
                        new
                        {
                            Id = new Guid("9ec80281-f74a-4c01-a577-53a6f22e5f18"),
                            ProductId = new Guid("a44ac53f-8536-40a6-85b2-b70db3c64c1a")
                        },
                        new
                        {
                            Id = new Guid("15f34f75-57c6-4709-8e70-fb44f6431a9d"),
                            ProductId = new Guid("56d9aa26-6971-435d-b1e3-6918ddc15072")
                        },
                        new
                        {
                            Id = new Guid("35500c66-b543-4789-8f49-b6908fe8ead4"),
                            ProductId = new Guid("84efa03f-b036-44cc-90c7-1b56162477ef")
                        },
                        new
                        {
                            Id = new Guid("2ad974e8-86dd-4cf2-bb2a-5aa6978c73f9"),
                            ProductId = new Guid("7538ebcc-92a5-4205-9170-8721e25d2455")
                        },
                        new
                        {
                            Id = new Guid("cce407fd-6093-4de2-9c2e-6a7ba0ee9319"),
                            ProductId = new Guid("afc6cbed-ccf0-4683-8a92-0c8e0995e5c7")
                        },
                        new
                        {
                            Id = new Guid("a96eb04c-cecc-4b1b-a51a-1ad31658e58f"),
                            ProductId = new Guid("62f2448a-c310-452d-afc0-f3a95e9e872a")
                        },
                        new
                        {
                            Id = new Guid("59c9ca7d-8c05-4541-8801-fa122a43a601"),
                            ProductId = new Guid("36883096-52c7-488a-94f1-0539a489f70d")
                        },
                        new
                        {
                            Id = new Guid("8e2d698b-140a-4a59-bafb-e52d8a6438c4"),
                            ProductId = new Guid("89a26fe3-6e0b-4294-b305-1f6d6fa06a59")
                        },
                        new
                        {
                            Id = new Guid("4346fd91-ead1-4dcc-911c-a7c515889578"),
                            ProductId = new Guid("c1551edb-d4f5-402d-ba14-d607e2daf707")
                        },
                        new
                        {
                            Id = new Guid("ebbfe919-bf0f-4c7a-9368-9d3083288dff"),
                            ProductId = new Guid("170d6671-45e0-4e64-90ad-aad7fe9ebf1d")
                        },
                        new
                        {
                            Id = new Guid("747e022a-8fa6-4c69-86db-e0c09dba0ad2"),
                            ProductId = new Guid("04b4acc0-e4f3-4d16-9807-cd6a91f9445c")
                        },
                        new
                        {
                            Id = new Guid("3907a6a6-eedb-44c0-8b19-cebae4da8e4a"),
                            ProductId = new Guid("fcbf01ea-4fa2-4ad0-8cc0-1787178a4b8c")
                        },
                        new
                        {
                            Id = new Guid("ec2b97b6-eb19-467b-bc66-959ea4bd01a9"),
                            ProductId = new Guid("afe3eb58-841d-4081-b1c4-e7e963279fc3")
                        },
                        new
                        {
                            Id = new Guid("8b093abe-5209-459d-9024-f4ede2b79961"),
                            ProductId = new Guid("7e768ae1-696c-4e18-96a8-3a16af240f48")
                        },
                        new
                        {
                            Id = new Guid("9c0cfd62-4f20-4a1b-a6ea-7f3c857d5260"),
                            ProductId = new Guid("8615a7a3-078b-45c8-9d6a-831e125e4916")
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef566634-0b1a-4aad-a3fc-3bb1572c274b"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Cotton Keyboard",
                            Price = 109.90m
                        },
                        new
                        {
                            Id = new Guid("2e4bf7a5-c43c-4280-8ed8-5dcddfb9bfab"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Soft Table",
                            Price = 12.20m
                        },
                        new
                        {
                            Id = new Guid("5db2271e-a20d-4a4e-90d4-dbf4a08a2c0f"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Licensed Steel Chair",
                            Price = 382.71m
                        },
                        new
                        {
                            Id = new Guid("21dd46a4-ad83-4c36-867a-aa01620ef9ee"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Gorgeous Metal Bike",
                            Price = 89.91m
                        },
                        new
                        {
                            Id = new Guid("3df20c2a-6bab-472a-b469-fb797fd5c8c2"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Plastic Gloves",
                            Price = 896.06m
                        },
                        new
                        {
                            Id = new Guid("2852e319-9a9d-40a6-9cd9-b1f2b33876b9"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Licensed Metal Sausages",
                            Price = 692.14m
                        },
                        new
                        {
                            Id = new Guid("a44ac53f-8536-40a6-85b2-b70db3c64c1a"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Frozen Computer",
                            Price = 341.71m
                        },
                        new
                        {
                            Id = new Guid("ff2ebfd5-49eb-40f3-9ab4-216ce34ab7ef"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Metal Fish",
                            Price = 93.97m
                        },
                        new
                        {
                            Id = new Guid("fcbf01ea-4fa2-4ad0-8cc0-1787178a4b8c"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Concrete Ball",
                            Price = 961.61m
                        },
                        new
                        {
                            Id = new Guid("751c2f3e-8df1-4a82-b7f1-7f5375d3e9c2"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Steel Shoes",
                            Price = 486.17m
                        },
                        new
                        {
                            Id = new Guid("170d6671-45e0-4e64-90ad-aad7fe9ebf1d"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Generic Rubber Car",
                            Price = 595.78m
                        },
                        new
                        {
                            Id = new Guid("3f455689-154a-4461-9241-1bab66de5495"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Practical Steel Table",
                            Price = 297.06m
                        },
                        new
                        {
                            Id = new Guid("afc6cbed-ccf0-4683-8a92-0c8e0995e5c7"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handcrafted Fresh Pants",
                            Price = 86.64m
                        },
                        new
                        {
                            Id = new Guid("c5eac18a-0c68-47ae-aee0-83ed87d5d28b"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Licensed Frozen Chips",
                            Price = 532.92m
                        },
                        new
                        {
                            Id = new Guid("d6eeacf3-abad-4c53-ab41-59a43801857b"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Generic Frozen Towels",
                            Price = 49.43m
                        },
                        new
                        {
                            Id = new Guid("72305cfe-bcbf-49bc-b9a2-40b22195f349"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licensed Steel Bacon",
                            Price = 340.57m
                        },
                        new
                        {
                            Id = new Guid("5f26001b-73b1-4483-8cb3-741fb23de570"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Licensed Wooden Soap",
                            Price = 50.35m
                        },
                        new
                        {
                            Id = new Guid("757a63d5-4367-4c5c-98a1-bffb60172f15"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incredible Fresh Mouse",
                            Price = 908.78m
                        },
                        new
                        {
                            Id = new Guid("aa5eb30d-dfff-468f-9e75-7dd99135785d"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Licensed Concrete Tuna",
                            Price = 440.49m
                        },
                        new
                        {
                            Id = new Guid("3956c3d8-aa5f-48d4-8428-65fe82e40c25"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Rustic Frozen Fish",
                            Price = 177.17m
                        },
                        new
                        {
                            Id = new Guid("95ccc587-3451-4816-b118-440c82846109"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Steel Gloves",
                            Price = 893.44m
                        },
                        new
                        {
                            Id = new Guid("d24f5b95-3d3d-4b6f-a693-4d3135ed7e1b"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handcrafted Steel Table",
                            Price = 784.56m
                        },
                        new
                        {
                            Id = new Guid("db51a931-d057-42d7-b632-7b8c7e14d190"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantastic Concrete Tuna",
                            Price = 501.81m
                        },
                        new
                        {
                            Id = new Guid("c6ee0204-703d-424e-b012-eed78b6885b5"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Sleek Plastic Fish",
                            Price = 780.59m
                        },
                        new
                        {
                            Id = new Guid("f33eff8e-e358-4617-b442-ed82b3622f8d"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Refined Metal Hat",
                            Price = 757.31m
                        },
                        new
                        {
                            Id = new Guid("4396694e-958c-4bbe-a4e2-c8d7ff8e8ce9"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incredible Plastic Keyboard",
                            Price = 883.38m
                        },
                        new
                        {
                            Id = new Guid("fae36503-1517-41b1-91b0-173e7cea66cc"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Unbranded Plastic Shirt",
                            Price = 711.48m
                        },
                        new
                        {
                            Id = new Guid("281fa34f-3c3e-4d66-b5eb-a8672d3fb602"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handmade Fresh Cheese",
                            Price = 366.69m
                        },
                        new
                        {
                            Id = new Guid("d8bdd3f3-0b97-4110-8233-b06bc1abf3d7"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Intelligent Granite Pants",
                            Price = 552.24m
                        },
                        new
                        {
                            Id = new Guid("a4f0546b-e584-4d0d-b482-75a2df1bfcd7"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Awesome Rubber Salad",
                            Price = 951.85m
                        },
                        new
                        {
                            Id = new Guid("5a2bb5a9-3f55-411f-af4f-9cd45bbf1e4f"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refined Concrete Bike",
                            Price = 298.61m
                        },
                        new
                        {
                            Id = new Guid("94f11d67-56da-4bd2-ad3a-d6030ad5a577"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Granite Car",
                            Price = 553.88m
                        },
                        new
                        {
                            Id = new Guid("99fd2bb4-e678-4874-b081-2d0b961aa375"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Fantastic Frozen Bike",
                            Price = 898.73m
                        },
                        new
                        {
                            Id = new Guid("8615a7a3-078b-45c8-9d6a-831e125e4916"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Small Fresh Car",
                            Price = 755.23m
                        },
                        new
                        {
                            Id = new Guid("2734d4ec-6ddc-4d6b-aba2-80b0b0ce7142"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Generic Granite Chair",
                            Price = 545.90m
                        },
                        new
                        {
                            Id = new Guid("89a26fe3-6e0b-4294-b305-1f6d6fa06a59"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantastic Plastic Pizza",
                            Price = 226.57m
                        },
                        new
                        {
                            Id = new Guid("f2d23011-a3ab-4564-ab05-cd69fdb1a87b"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handmade Cotton Ball",
                            Price = 9.72m
                        },
                        new
                        {
                            Id = new Guid("2e56538b-5589-401c-8d1a-c034fef15d3c"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Wooden Cheese",
                            Price = 803.99m
                        },
                        new
                        {
                            Id = new Guid("55d8bbdb-f798-439a-8cc3-58b9716f72e6"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Intelligent Soft Fish",
                            Price = 986.90m
                        },
                        new
                        {
                            Id = new Guid("880cb16a-0190-45a2-9afa-70f6bd4df394"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Incredible Concrete Shirt",
                            Price = 540.73m
                        },
                        new
                        {
                            Id = new Guid("f2d7a16e-5dbd-4e73-b965-d01ce1a90b26"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Granite Pizza",
                            Price = 309.81m
                        },
                        new
                        {
                            Id = new Guid("c8693996-14c1-4260-9a84-eac33f01622c"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantastic Wooden Keyboard",
                            Price = 891.30m
                        },
                        new
                        {
                            Id = new Guid("c3babf65-6cbc-4775-99f5-732365cbac80"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Awesome Metal Pants",
                            Price = 801.20m
                        },
                        new
                        {
                            Id = new Guid("af08bec1-b8d7-4718-bfb7-6eade8c3f6dc"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Tasty Metal Chips",
                            Price = 206.31m
                        },
                        new
                        {
                            Id = new Guid("70559fd9-637a-4b7a-9e66-9d15c1a7707a"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Steel Cheese",
                            Price = 532.30m
                        },
                        new
                        {
                            Id = new Guid("8df0db69-6a0c-4312-a15c-659e66c16e0a"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Refined Soft Pizza",
                            Price = 221.32m
                        },
                        new
                        {
                            Id = new Guid("75c94cdd-c710-4917-b3fc-6ed5d9dfc76c"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Rustic Frozen Computer",
                            Price = 523.04m
                        },
                        new
                        {
                            Id = new Guid("c1551edb-d4f5-402d-ba14-d607e2daf707"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gorgeous Granite Keyboard",
                            Price = 650.35m
                        },
                        new
                        {
                            Id = new Guid("9f888ca1-56e5-4b88-b658-7654250009cf"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Sleek Frozen Chicken",
                            Price = 259.41m
                        },
                        new
                        {
                            Id = new Guid("afe3eb58-841d-4081-b1c4-e7e963279fc3"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Cotton Salad",
                            Price = 7.16m
                        },
                        new
                        {
                            Id = new Guid("c935f927-dbff-4a15-998f-c43fae82686f"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handcrafted Concrete Table",
                            Price = 628.16m
                        },
                        new
                        {
                            Id = new Guid("56d9aa26-6971-435d-b1e3-6918ddc15072"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Soft Tuna",
                            Price = 453.12m
                        },
                        new
                        {
                            Id = new Guid("207f5b5e-c91c-4a17-8768-bacc83811e90"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Awesome Plastic Chips",
                            Price = 719.71m
                        },
                        new
                        {
                            Id = new Guid("62f2448a-c310-452d-afc0-f3a95e9e872a"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Awesome Rubber Mouse",
                            Price = 564.96m
                        },
                        new
                        {
                            Id = new Guid("a00a44fc-59c8-4457-b490-ce736284b9b3"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Practical Granite Car",
                            Price = 692.84m
                        },
                        new
                        {
                            Id = new Guid("d68d8ffc-a9a4-4371-8330-4a2d7700980b"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Tasty Plastic Pants",
                            Price = 965.27m
                        },
                        new
                        {
                            Id = new Guid("1f65d25d-6134-4b4d-a0e9-23d63f56b114"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Practical Fresh Shoes",
                            Price = 533.70m
                        },
                        new
                        {
                            Id = new Guid("51a7e236-fc50-4159-be4b-e6c1b426a1ab"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Unbranded Granite Towels",
                            Price = 865.10m
                        },
                        new
                        {
                            Id = new Guid("0b9c7e8d-e6fc-43a9-8b3f-a66b4582fad9"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Sleek Fresh Hat",
                            Price = 85.84m
                        },
                        new
                        {
                            Id = new Guid("e7f2b5e3-db46-4d84-af30-9b1ced62a9d8"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Intelligent Frozen Bacon",
                            Price = 680.75m
                        },
                        new
                        {
                            Id = new Guid("85b757da-1e19-4163-b7c5-0570727d3887"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Concrete Soap",
                            Price = 556.63m
                        },
                        new
                        {
                            Id = new Guid("910ca9e6-c3f9-4b65-9ae8-34646870695c"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Intelligent Concrete Keyboard",
                            Price = 686.03m
                        },
                        new
                        {
                            Id = new Guid("84fd00e6-586b-4333-a806-a0b524a3b232"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Incredible Cotton Tuna",
                            Price = 32.34m
                        },
                        new
                        {
                            Id = new Guid("966c6717-c62b-4f4a-8780-a899e60cf011"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Fresh Pizza",
                            Price = 792.60m
                        },
                        new
                        {
                            Id = new Guid("7988059a-be79-465b-b44c-1a61bdb59cf1"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Frozen Tuna",
                            Price = 68.88m
                        },
                        new
                        {
                            Id = new Guid("c7390686-dbe1-4732-8b92-ffe5c86c1746"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Awesome Frozen Towels",
                            Price = 514.51m
                        },
                        new
                        {
                            Id = new Guid("36dd1df2-41e6-47e5-bc66-e7dfadb77e70"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Granite Chicken",
                            Price = 949.01m
                        },
                        new
                        {
                            Id = new Guid("7aa3c047-b801-4374-8180-7dca75b1a718"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Rustic Plastic Chicken",
                            Price = 344.74m
                        },
                        new
                        {
                            Id = new Guid("36883096-52c7-488a-94f1-0539a489f70d"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handmade Cotton Chicken",
                            Price = 559.27m
                        },
                        new
                        {
                            Id = new Guid("65a286a8-ccb1-4b8d-a36f-990fc4511ebf"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Rustic Concrete Salad",
                            Price = 418.78m
                        },
                        new
                        {
                            Id = new Guid("8fb764c3-63d9-4456-8e90-a5d8db79ab8d"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Wooden Shoes",
                            Price = 629.03m
                        },
                        new
                        {
                            Id = new Guid("abf7294f-426d-43c3-847f-e365f10a8866"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Small Rubber Keyboard",
                            Price = 4.42m
                        },
                        new
                        {
                            Id = new Guid("f13c577e-1f72-45a3-aff0-30b929242b76"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Intelligent Rubber Salad",
                            Price = 716.51m
                        },
                        new
                        {
                            Id = new Guid("87d63569-4b9e-44aa-bc8e-5d8fa2b2a51d"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Licensed Metal Pants",
                            Price = 863.07m
                        },
                        new
                        {
                            Id = new Guid("f6503aa7-5815-4445-baf5-9b57be57d5b1"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Fantastic Wooden Gloves",
                            Price = 58.21m
                        },
                        new
                        {
                            Id = new Guid("7e768ae1-696c-4e18-96a8-3a16af240f48"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handcrafted Plastic Cheese",
                            Price = 939.59m
                        },
                        new
                        {
                            Id = new Guid("a0674f51-9cb8-4c60-b009-0ff94d48b7ba"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Incredible Steel Computer",
                            Price = 190.97m
                        },
                        new
                        {
                            Id = new Guid("26d5b702-214c-4e07-88e4-4f647d77e4bc"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refined Steel Bacon",
                            Price = 931.62m
                        },
                        new
                        {
                            Id = new Guid("5b6fc1c4-88b3-40da-8c9e-5dc0d8d5b5cd"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Awesome Wooden Sausages",
                            Price = 115.73m
                        },
                        new
                        {
                            Id = new Guid("db25efaf-4958-4671-8f8e-5fa97464a243"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Ergonomic Granite Pants",
                            Price = 777.90m
                        },
                        new
                        {
                            Id = new Guid("84efa03f-b036-44cc-90c7-1b56162477ef"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Fresh Bike",
                            Price = 59.83m
                        },
                        new
                        {
                            Id = new Guid("118afaa1-71b1-457c-9b6f-20fb21167b4d"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Rustic Soft Hat",
                            Price = 967.89m
                        },
                        new
                        {
                            Id = new Guid("dbbf57b6-035f-4492-9538-9336f185282c"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Fresh Ball",
                            Price = 690.22m
                        },
                        new
                        {
                            Id = new Guid("bfe642ae-b013-4b57-9afd-4e156fb30af5"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rustic Granite Computer",
                            Price = 846.32m
                        },
                        new
                        {
                            Id = new Guid("87977af4-3963-4d87-9115-7d7a032d8452"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Fresh Chicken",
                            Price = 305.78m
                        },
                        new
                        {
                            Id = new Guid("d2f537ea-f360-4291-9a2e-8b2e419f6794"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Intelligent Concrete Fish",
                            Price = 946.12m
                        },
                        new
                        {
                            Id = new Guid("42599a4b-43ee-4762-af65-8fc107bfa481"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Intelligent Frozen Tuna",
                            Price = 492.92m
                        },
                        new
                        {
                            Id = new Guid("31d7eb7c-96a2-4e9c-9d16-41df9c6fb866"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Practical Fresh Hat",
                            Price = 43.36m
                        },
                        new
                        {
                            Id = new Guid("b17e13ee-e85f-4e0d-8865-6ca1abb9c599"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonomic Granite Chips",
                            Price = 224.67m
                        },
                        new
                        {
                            Id = new Guid("e1e42e20-a837-4c91-9bb2-b5ff0702f085"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handmade Fresh Keyboard",
                            Price = 943.23m
                        },
                        new
                        {
                            Id = new Guid("77056e1d-bc25-4983-9738-09127b567cbb"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Generic Plastic Mouse",
                            Price = 30.44m
                        },
                        new
                        {
                            Id = new Guid("7538ebcc-92a5-4205-9170-8721e25d2455"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Awesome Wooden Shoes",
                            Price = 855.56m
                        },
                        new
                        {
                            Id = new Guid("29e392c9-3375-4a60-9322-a72154b4b83f"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Unbranded Steel Tuna",
                            Price = 782.81m
                        },
                        new
                        {
                            Id = new Guid("4ba1ec54-d5f8-4b90-98db-fbc14d943a03"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handmade Wooden Mouse",
                            Price = 253.53m
                        },
                        new
                        {
                            Id = new Guid("486891b5-7d73-4c4c-a689-9822ff16bd64"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Incredible Frozen Pants",
                            Price = 771.08m
                        },
                        new
                        {
                            Id = new Guid("2ce63658-f846-48fb-8021-2cdbdf658bdc"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Intelligent Frozen Chips",
                            Price = 570.82m
                        },
                        new
                        {
                            Id = new Guid("1c681462-8681-4690-a689-5ac18ec656ae"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Incredible Steel Pizza",
                            Price = 344.93m
                        },
                        new
                        {
                            Id = new Guid("b5a53c24-820b-4499-a14a-11da946a04fb"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Licensed Soft Pants",
                            Price = 932.27m
                        },
                        new
                        {
                            Id = new Guid("04b4acc0-e4f3-4d16-9807-cd6a91f9445c"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Cotton Bike",
                            Price = 126.41m
                        },
                        new
                        {
                            Id = new Guid("80e192c5-5c04-4cca-8f21-caaf0cafcdef"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Small Fresh Car",
                            Price = 485.62m
                        });
                });

            modelBuilder.Entity("IOM.Core.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("IOM.Core.Models.SupplierProduct", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SupplierProducts");
                });

            modelBuilder.Entity("IOM.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.HasOne("IOM.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceItem", b =>
                {
                    b.HasOne("IOM.Core.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Item", "Item")
                        .WithMany("InvoiceItem")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IOM.Core.Models.InvoiceSupplier", b =>
                {
                    b.HasOne("IOM.Core.Models.Invoice", "Invoice")
                        .WithMany("InvoiceSupplier")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Supplier", "Supplier")
                        .WithMany("InvoiceSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.HasOne("IOM.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOM.Core.Models.SupplierProduct", b =>
                {
                    b.HasOne("IOM.Core.Models.Product", "Product")
                        .WithMany("SupplierProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOM.Core.Models.Supplier", "Supplier")
                        .WithMany("SupplierProduct")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItem");

                    b.Navigation("InvoiceSupplier");
                });

            modelBuilder.Entity("IOM.Core.Models.Item", b =>
                {
                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("IOM.Core.Models.Product", b =>
                {
                    b.Navigation("SupplierProduct");
                });

            modelBuilder.Entity("IOM.Core.Models.Supplier", b =>
                {
                    b.Navigation("InvoiceSuppliers");

                    b.Navigation("SupplierProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
